[tool.poetry]
name = "polybar-gmail"
version = "0.2.0"
description = "Polybar module to show unread messages from Gmail"
authors = ["Vyacheslav Konovalov <crabvk@protonmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
google-api-python-client = "^2.13.0"
google-auth-httplib2 = "^0.1.0"
google-auth-oauthlib = "^0.4.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.1.0"]
build-backend = "poetry.masonry.api"
